export const mockedCelebrities = [
  {
    adult: false,
    gender: 2,
    id: 2524,
    known_for_department: "Acting",
    name: "Tom Hardy",
    original_name: "Tom Hardy",
    popularity: 65.443,
    profile_path: "/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg",
    known_for: [
      {
        backdrop_path: "/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg",
        id: 76341,
        title: "Mad Max: Fury Road",
        original_title: "Mad Max: Fury Road",
        overview:
          "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
        poster_path: "/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 12, 878],
        popularity: 95.494,
        release_date: "2015-05-13",
        video: false,
        vote_average: 7.6,
        vote_count: 22471,
      },
      {
        backdrop_path: "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
        id: 335983,
        title: "Venom",
        original_title: "Venom",
        overview:
          "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
        poster_path: "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [878, 28],
        popularity: 425.779,
        release_date: "2018-09-28",
        video: false,
        vote_average: 6.828,
        vote_count: 15731,
      },
      {
        backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
        id: 580489,
        title: "Venom: Let There Be Carnage",
        original_title: "Venom: Let There Be Carnage",
        overview:
          "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
        poster_path: "/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [878, 28, 12],
        popularity: 351.03,
        release_date: "2021-09-30",
        video: false,
        vote_average: 6.796,
        vote_count: 9982,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 500,
    known_for_department: "Acting",
    name: "Tom Cruise",
    original_name: "Tom Cruise",
    popularity: 86.151,
    profile_path: "/3mShHjSQR7NXOVbdTu5rT2Qd0MN.jpg",
    known_for: [
      {
        backdrop_path: "/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg",
        id: 137113,
        title: "Edge of Tomorrow",
        original_title: "Edge of Tomorrow",
        overview:
          "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
        poster_path: "/xjw5trHV7Mwo61P0kCTy8paEkgO.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 878],
        popularity: 55.091,
        release_date: "2014-05-27",
        video: false,
        vote_average: 7.623,
        vote_count: 13714,
      },
      {
        backdrop_path: "/A6wFgFFEgymebp518fcsa71jnSu.jpg",
        id: 75612,
        title: "Oblivion",
        original_title: "Oblivion",
        overview:
          "Jack Harper is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete. His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft. Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.",
        poster_path: "/eO3r38fwnhb58M1YgcjQBd3VNcp.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 878, 12, 9648],
        popularity: 31.556,
        release_date: "2013-04-10",
        video: false,
        vote_average: 6.6,
        vote_count: 10569,
      },
      {
        backdrop_path: "/ih4lZkUpmSE7AP3maymiO72xJ1z.jpg",
        id: 56292,
        title: "Mission: Impossible - Ghost Protocol",
        original_title: "Mission: Impossible - Ghost Protocol",
        overview:
          "Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.",
        poster_path: "/eRZTGx7GsiKqPch96k27LK005ZL.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 53, 12],
        popularity: 53.889,
        release_date: "2011-12-07",
        video: false,
        vote_average: 7.09,
        vote_count: 9789,
      },
    ],
  },
];

export const apiData = {
  page: 1,
  results: mockedCelebrities,
  total_pages: 500,
  total_results: 10000,
};
